version: "3.8"

services:
  mysql:
    image: mysql:latest
    restart: always
    networks:
      my_network:
        ipv4_address: 172.18.0.2
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: tigerhall
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  gin-app:
    image: tigerhall-backend
    networks:
      my_network:
        ipv4_address: 172.18.0.3
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    env_file:
      - .env.development

networks:
  my_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16

volumes:
  mysql-data:
